services:
 testnet-client:
    image: registry.cn-hangzhou.aliyuncs.com/testnet0/testnet_client:latest
    container_name: testnet-client
    environment:
      - MYSQL_URL=jdbc:mysql://${IP}:33306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=${IP}
      - REDIS_PORT=36379
      - TESTNET_CLIENT_VERSION=V1.2
      - TESTNET_RESULT_PATH=/testnet-client/results/
      - TESTNET_CLIENT_NAME=${CLIENT_NAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
