services:
 testnet-client:
    image: registry.cn-hangzhou.aliyuncs.com/testnet0/testnet_client:1.0
    container_name: testnet-client
    environment:
      - MYSQL_URL=jdbc:mysql://替换为你的IP:33306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      - MYSQL_PASSWORD=替换为目录下.env中的Mysql密码
      - REDIS_HOST=替换为你的IP
      - REDIS_PORT=36379
      - TESTNET_CLIENT_NAME=替换为客户端名称
      - REDIS_PASSWORD=替换为目录下.env中的Redis密码
    restart: always
