networks:
  testnet:
    name: testnet
    driver: bridge
    ipam:
      driver: default
      config:
        - gateway: ${SUBNET_PREFIX:?SUBNET_PREFIX required}.1
          subnet: ${SUBNET_PREFIX}.0/24
    driver_opts:
      com.docker.network.bridge.name: testnet
services:
  testnet-mysql:
    image: registry.cn-hangzhou.aliyuncs.com/testnet0/mysql:8.3
    container_name: testnet-mysql
    networks:
      testnet:
        ipv4_address: ${SUBNET_PREFIX}.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --lower_case_table_names=1 --max_allowed_packet=128M --default-authentication-plugin=caching_sha2_password
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "33306:3306"

  testnet-redis:
    image: registry.cn-hangzhou.aliyuncs.com/testnet0/redis:5.0
    container_name: testnet-redis
    networks:
      testnet:
        ipv4_address: ${SUBNET_PREFIX}.3
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "36379:6379"
    restart: always

  testnet-es:
    image: registry.cn-hangzhou.aliyuncs.com/testnet0/es:7.10.1
    container_name: testnet-es
    networks:
      testnet:
        ipv4_address: ${SUBNET_PREFIX}.4
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    restart: always
  testnet-server:
    image: registry.cn-hangzhou.aliyuncs.com/testnet0/testnet_server:1.0
    container_name: testnet-server
    networks:
      testnet:
        ipv4_address: ${SUBNET_PREFIX}.5
    environment:
      - MYSQL_URL=jdbc:mysql://${SUBNET_PREFIX}.2:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=${SUBNET_PREFIX}.3
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ES_HOST=${SUBNET_PREFIX}.4:9200
    depends_on:
      - testnet-mysql
      - testnet-redis
      - testnet-es
    restart: always

  testnet-frontend:
    container_name: testnet-frontend
    image: registry.cn-hangzhou.aliyuncs.com/testnet0/testnet_frontend:1.0
    networks:
      testnet:
        ipv4_address: ${SUBNET_PREFIX}.6
    ports:
      - "8099:80"
    restart: always
    depends_on:
      - testnet-server
  testnet-client:
    image: registry.cn-hangzhou.aliyuncs.com/testnet0/testnet_client:1.0
    networks:
      testnet:
        ipv4_address: ${SUBNET_PREFIX}.7
    container_name: testnet-client
    environment:
      - MYSQL_URL=jdbc:mysql://${SUBNET_PREFIX}.2:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=${SUBNET_PREFIX}.3
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
    restart: always
